nuts <- tibble::tribble(
    ~Code,     ~Country,          ~NUTS.1,            ~NUTS.2,                    ~NUTS.3,
     "AT", "ÖSTERREICH",               NA,                 NA,                         NA,
    "AT1",           NA,     "ÖSTERREICH",                 NA,                         NA,
   "AT11",           NA,               NA,       "Burgenland",                         NA,
  "AT111",           NA,               NA,                 NA,         "Mittelburgenland",
  "AT112",           NA,               NA,                 NA,           "Nordburgenland",
  "AT113",           NA,               NA,                 NA,            "Südburgenland",
   "AT12",           NA,               NA, "Niederösterreich",                         NA,
  "AT121",           NA,               NA,                 NA,  "Mostviertel-Eisenwurzen",
  "AT122",           NA,               NA,                 NA,     "Niederösterreich-Süd",
  "AT123",           NA,               NA,                 NA,             "Sankt Pölten",
  "AT124",           NA,               NA,                 NA,              "Waldviertel",
  "AT125",           NA,               NA,                 NA,              "Weinviertel",
  "AT126",           NA,               NA,                 NA,   "Wiener Umland/Nordteil",
  "AT127",           NA,               NA,                 NA,    "Wiener Umland/Südteil",
   "AT13",           NA,               NA,             "Wien",                         NA,
  "AT130",           NA,               NA,                 NA,                     "Wien",
    "AT2",           NA,  "SÜDÖSTERREICH",                 NA,                         NA,
   "AT21",           NA,               NA,          "Kärnten",                         NA,
  "AT211",           NA,               NA,                 NA,       "Klagenfurt-Villach",
  "AT212",           NA,               NA,                 NA,              "Oberkärnten",
  "AT213",           NA,               NA,                 NA,             "Unterkärnten",
   "AT22",           NA,               NA,       "Steiermark",                         NA,
  "AT221",           NA,               NA,                 NA,                     "Graz",
  "AT222",           NA,               NA,                 NA,                   "Liezen",
  "AT223",           NA,               NA,                 NA,  "Östliche Obersteiermark",
  "AT224",           NA,               NA,                 NA,            "Oststeiermark",
  "AT225",           NA,               NA,                 NA,  "West- und Südsteiermark",
  "AT226",           NA,               NA,                 NA, "Westliche Obersteiermark",
    "AT3",           NA, "WESTÖSTERREICH",                 NA,                         NA,
   "AT31",           NA,               NA,   "Oberösterreich",                         NA,
  "AT311",           NA,               NA,                 NA,                "Innvierte",
  "AT312",           NA,               NA,                 NA,                "Linz-Wels",
  "AT313",           NA,               NA,                 NA,              "Mühlviertel",
  "AT314",           NA,               NA,                 NA,          "Steyr-Kirchdorf",
  "AT315",           NA,               NA,                 NA,             "Traunviertel",
   "AT32",           NA,               NA,         "Salzburg",                         NA,
  "AT321",           NA,               NA,                 NA,                   "Lungau",
  "AT322",           NA,               NA,                 NA,           "Pinzgau-Pongau",
  "AT323",           NA,               NA,                 NA,    "Salzburg und Umgebung",
   "AT33",           NA,               NA,            "Tirol",                         NA,
  "At331",           NA,               NA,                 NA,                "Außerfern",
  "AT332",           NA,               NA,                 NA,                "Innsbruck",
  "AT333",           NA,               NA,                 NA,                 "Osttirol",
  "AT334",           NA,               NA,                 NA,         "Tiroler Oberland",
  "AT335",           NA,               NA,                 NA,        "Tiroler Unterland",
   "AT34",           NA,               NA,       "Vorarlberg",                         NA,
  "AT341",           NA,               NA,                 NA,   "Bludenz-Bregenzer Wald",
  "AT342",           NA,               NA,                 NA,                 "Rheintal"
  )

nuts2 <- nuts %>% filter(str_length(Code) == 4) %>% select(Code, NUTS.2) %>% na.omit()
nuts <- nuts %>% select(reg = Code, reg_name = NUTS.3) %>% na.omit() %>% 
  mutate(Code = str_sub(reg, 1, 4)) %>% left_join(nuts2, by = "Code")

